language: python

python:
    - '3.5'

jobs:
  include:
    - stage: prepare
      name: "Setup"
      script: pip3 install -r requirements.txt
    - stage: test
      name: "Lint"
      script: flake8
    - stage: test
      name: "Type Checking"
      script: mypy lib/wit/*.py
    - stage: test
      name: "Regression Tests"
      script: ./t/regress.sh
